version: '3.1'

services:
  mysql-server:
    container_name: mysql
    image: mysql/mysql-server:5.7
    # command:
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=@qweasdzxc
      - MYSQL_DATABASE=docker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    restart: on-failure
