version: '3.1'

services:
  mysql-server:
    container_name: mysql
    image: mysql/mysql-server:5.7
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=@qweasdzxc
      - MYSQL_DATABASE=docker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Project/laravel-world:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    container_name: php-fpm
    image: php:fpm
    volumes:
      - ~/Project/laravel-world:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
