version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ~/Documents/Project/html:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
